"""collaboration_audit

Revision ID: 0042f75ab123
Revises: 13b45b85e1dc
Create Date: 2026-08-25 23:45:59.247763

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0042f75ab123"
down_revision: str | Sequence[str] | None = "13b45b85e1dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_actor_id', 'audit_events', ['actor_id'], unique=False)
    op.create_index('ix_audit_events_clinic_id', 'audit_events', ['clinic_id'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_patient_id', 'audit_events', ['patient_id'], unique=False)
    op.create_index('ix_audit_events_resource', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('parent_comment_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_author_id', 'comments', ['author_id'], unique=False)
    op.create_index('ix_comments_entry_id', 'comments', ['entry_id'], unique=False)
    op.create_index('ix_comments_parent_comment_id', 'comments', ['parent_comment_id'], unique=False)
    op.create_index('ix_comments_resolved_by_id', 'comments', ['resolved_by_id'], unique=False)
    op.create_table('entry_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('changed_by_id', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('change_reason', sa.Enum('created', 'manual_edit', 'revert', 'conflict_resolution', 'system_correction', name='change_reason', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_version', sa.Integer(), nullable=True),
    sa.Column('reverted_from_version', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.CheckConstraint('(version_number = 1 AND source_version IS NULL) OR (version_number > 1 AND source_version >= 1 AND source_version < version_number)', name='ck_entry_versions_source_precedes_version'),
    sa.CheckConstraint('length(content_hash) = 64', name='ck_entry_versions_sha256_length'),
    sa.CheckConstraint('version_number >= 1', name='ck_entry_versions_number_positive'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'version_number', name='uq_entry_versions_entry_version')
    )
    op.create_index('ix_entry_versions_changed_by_id', 'entry_versions', ['changed_by_id'], unique=False)
    op.create_index('ix_entry_versions_entry_id', 'entry_versions', ['entry_id'], unique=False)
    op.create_table('importance_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('highlight_id', sa.Uuid(), nullable=True),
    sa.Column('entity_key', sa.Text(), nullable=False),
    sa.Column('action', sa.Enum('accept', 'reject', 'edit', 'comment', name='feedback_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('ranking_delta', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('ranking_delta >= -1 AND ranking_delta <= 1', name='ck_importance_feedback_delta_range'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_importance_feedback_actor_id', 'importance_feedback', ['actor_id'], unique=False)
    op.create_index('ix_importance_feedback_highlight_id', 'importance_feedback', ['highlight_id'], unique=False)
    op.create_index('ix_importance_feedback_patient_entity', 'importance_feedback', ['patient_id', 'entity_key'], unique=False)
    op.create_index('ix_importance_feedback_patient_id', 'importance_feedback', ['patient_id'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        for table in ("audit_events", "comments", "entry_versions", "importance_feedback"):
            op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_importance_feedback_patient_id', table_name='importance_feedback')
    op.drop_index('ix_importance_feedback_patient_entity', table_name='importance_feedback')
    op.drop_index('ix_importance_feedback_highlight_id', table_name='importance_feedback')
    op.drop_index('ix_importance_feedback_actor_id', table_name='importance_feedback')
    op.drop_table('importance_feedback')
    op.drop_index('ix_entry_versions_entry_id', table_name='entry_versions')
    op.drop_index('ix_entry_versions_changed_by_id', table_name='entry_versions')
    op.drop_table('entry_versions')
    op.drop_index('ix_comments_resolved_by_id', table_name='comments')
    op.drop_index('ix_comments_parent_comment_id', table_name='comments')
    op.drop_index('ix_comments_entry_id', table_name='comments')
    op.drop_index('ix_comments_author_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_audit_events_resource', table_name='audit_events')
    op.drop_index('ix_audit_events_patient_id', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_clinic_id', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_id', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
