"""clinical_context

Revision ID: 13b45b85e1dc
Revises: 13e122c49093
Create Date: 2026-08-25 23:40:40.706105

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13b45b85e1dc"
down_revision: str | Sequence[str] | None = "13e122c49093"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('fact_type', sa.Enum('symptom', 'medication', 'allergy', 'diagnosis', 'vital', 'plan', name='fact_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('entity_name', sa.Text(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risk_level', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('persistence_type', sa.Enum('transient', 'persistent', name='persistence_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('source_start', sa.Integer(), nullable=True),
    sa.Column('source_end', sa.Integer(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('review_status', sa.Enum('suggested', 'confirmed', 'rejected', name='fact_review_status', native_enum=False, create_constraint=True), server_default='suggested', nullable=False),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(source_start IS NULL AND source_end IS NULL) OR (source_start >= 0 AND source_end > source_start)', name='ck_clinical_facts_source_span'),
    sa.CheckConstraint('extraction_confidence >= 0 AND extraction_confidence <= 1', name='ck_clinical_facts_confidence_range'),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clinical_facts_entry_id', 'clinical_facts', ['entry_id'], unique=False)
    op.create_index('ix_clinical_facts_patient_entity', 'clinical_facts', ['patient_id', 'entity_name'], unique=False)
    op.create_index('ix_clinical_facts_patient_id', 'clinical_facts', ['patient_id'], unique=False)
    op.create_index('ix_clinical_facts_reviewed_by_id', 'clinical_facts', ['reviewed_by_id'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('conflict_type', sa.Enum('medication_dose', name='conflict_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('entity_name', sa.Text(), nullable=False),
    sa.Column('conflicting_fact_id', sa.Uuid(), nullable=False),
    sa.Column('authoritative_fact_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('detected', 'resolved', 'dismissed', name='conflict_status', native_enum=False, create_constraint=True), server_default='detected', nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('conflicting_fact_id <> authoritative_fact_id', name='ck_conflicts_distinct_facts'),
    sa.ForeignKeyConstraint(['authoritative_fact_id'], ['clinical_facts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conflicting_fact_id'], ['clinical_facts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conflicts_authoritative_fact_id', 'conflicts', ['authoritative_fact_id'], unique=False)
    op.create_index('ix_conflicts_conflicting_fact_id', 'conflicts', ['conflicting_fact_id'], unique=False)
    op.create_index('ix_conflicts_patient_id', 'conflicts', ['patient_id'], unique=False)
    op.create_index('ix_conflicts_patient_status', 'conflicts', ['patient_id', 'status'], unique=False)
    op.create_index('ix_conflicts_resolved_by_id', 'conflicts', ['resolved_by_id'], unique=False)
    op.create_table('highlights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('clinical_fact_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('critical', 'recent_change', 'open_action', 'conflict', name='highlight_category', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='highlight_risk_level', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('risk_reason', sa.Text(), nullable=False),
    sa.Column('base_score', sa.Integer(), nullable=False),
    sa.Column('learned_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('suggested', 'accepted', 'rejected', 'archived', name='highlight_status', native_enum=False, create_constraint=True), server_default='suggested', nullable=False),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('learned_score >= 0 AND learned_score <= 3', name='ck_highlights_learning_range'),
    sa.ForeignKeyConstraint(['clinical_fact_id'], ['clinical_facts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_highlights_clinical_fact_id', 'highlights', ['clinical_fact_id'], unique=False)
    op.create_index('ix_highlights_patient_id', 'highlights', ['patient_id'], unique=False)
    op.create_index('ix_highlights_patient_status', 'highlights', ['patient_id', 'status'], unique=False)
    op.create_index('ix_highlights_reviewed_by_id', 'highlights', ['reviewed_by_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('source_entry_id', sa.Uuid(), nullable=False),
    sa.Column('source_fact_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='task_priority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'completed', name='task_status', native_enum=False, create_constraint=True), server_default='open', nullable=False),
    sa.Column('assigned_role', sa.Enum('patient', 'staff', 'clinician', 'admin', name='task_assigned_role', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('completed_by_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_entry_id'], ['entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_fact_id'], ['clinical_facts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_completed_by_id', 'tasks', ['completed_by_id'], unique=False)
    op.create_index('ix_tasks_patient_id', 'tasks', ['patient_id'], unique=False)
    op.create_index('ix_tasks_patient_status', 'tasks', ['patient_id', 'status'], unique=False)
    op.create_index('ix_tasks_source_entry_id', 'tasks', ['source_entry_id'], unique=False)
    op.create_index('ix_tasks_source_fact_id', 'tasks', ['source_fact_id'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        for table in ("clinical_facts", "conflicts", "highlights", "tasks"):
            op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_source_fact_id', table_name='tasks')
    op.drop_index('ix_tasks_source_entry_id', table_name='tasks')
    op.drop_index('ix_tasks_patient_status', table_name='tasks')
    op.drop_index('ix_tasks_patient_id', table_name='tasks')
    op.drop_index('ix_tasks_completed_by_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_highlights_reviewed_by_id', table_name='highlights')
    op.drop_index('ix_highlights_patient_status', table_name='highlights')
    op.drop_index('ix_highlights_patient_id', table_name='highlights')
    op.drop_index('ix_highlights_clinical_fact_id', table_name='highlights')
    op.drop_table('highlights')
    op.drop_index('ix_conflicts_resolved_by_id', table_name='conflicts')
    op.drop_index('ix_conflicts_patient_status', table_name='conflicts')
    op.drop_index('ix_conflicts_patient_id', table_name='conflicts')
    op.drop_index('ix_conflicts_conflicting_fact_id', table_name='conflicts')
    op.drop_index('ix_conflicts_authoritative_fact_id', table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index('ix_clinical_facts_reviewed_by_id', table_name='clinical_facts')
    op.drop_index('ix_clinical_facts_patient_id', table_name='clinical_facts')
    op.drop_index('ix_clinical_facts_patient_entity', table_name='clinical_facts')
    op.drop_index('ix_clinical_facts_entry_id', table_name='clinical_facts')
    op.drop_table('clinical_facts')
    # ### end Alembic commands ###
